### ISSUE TITLE
Meta JSON in readme.md needs updates

### ISSUE THREAD

**Issue by amirhadad** [scrapy-plugins/scrapy-splash#13]
Had to change:
    'splash': {
                    'endpoint': 'render.html',
                    'args': {'wait': 0.5}
    }
to:
    'splash': {
                    'endpoint': 'render.html',
                    'args': {'wait': '0.5'}
    }

in read me. Assuming same rule applies for the rest of the examples put on readme.md file.

**Comment by kmike** [comment]
Hey @amirhadad,
It is intended to work with `'wait': 0.5`. What error do you get?

**Comment by amirhadad** [comment]
The error I was getting was:

###### File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/utils/python.py", line 97, in unicode_to_str raise TypeError('unicode_to_str must receive a unicode or str object, got %s' % type(text).**name**)

###### exceptions.TypeError: unicode_to_str must receive a unicode or str object, got float

It was fixed after the changes I mentioned above was made.

**Comment by kmike** [comment]
Could you please paste the full traceback? Thanks!

**Comment by amirhadad** [comment]
@kmike ended up using PhontomJS as I had to emulate clicks on the page hence hard to regenerate the error.
If you read the last line of the exception it clearly says it expects a 'unicode or str' object, but it got a 'float' value. Give my mini change fixed it must be enough proof that it was root of the exception at least in my case.

**Comment by gabll** [comment]
I had the same error and after the change 0.5 -> '0.5' it works.
Thank you @amirhadad !

@kmike this is my copy-pasted traceback:
2015-03-15 20:10:10-0400 [my_spider] ERROR: Spider error processing <GET http://www.mydomain.com.html>
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
        taskObj._oneWorkUnit()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 495, in _oneWorkUnit
        failLater)
    --- <exception caught here> ---
      File "/usr/lib/pymodules/python2.7/scrapy/utils/defer.py", line 96, in iter_errback
        yield next(it)
    exceptions.GeneratorExit: 

2015-03-15 20:10:10-0400 [-] ERROR: Unhandled error in Deferred:
2015-03-15 20:10:10-0400 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(_call.args, *_call.kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
        taskObj._oneWorkUnit()
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
        result = next(self._iterator)
      File "/usr/lib/pymodules/python2.7/scrapy/utils/defer.py", line 57, in <genexpr>
        work = (callable(elem, _args, *_named) for elem in iterable)
      File "/usr/lib/pymodules/python2.7/scrapy/core/scraper.py", line 165, in _process_spidermw_output
        self.crawler.engine.crawl(request=output, spider=spider)
      File "/usr/lib/pymodules/python2.7/scrapy/core/engine.py", line 176, in crawl
        self.schedule(request, spider)
      File "/usr/lib/pymodules/python2.7/scrapy/core/engine.py", line 182, in schedule
        return self.slot.scheduler.enqueue_request(request)
      File "/usr/lib/pymodules/python2.7/scrapy/core/scheduler.py", line 48, in enqueue_request
        if not request.dont_filter and self.df.request_seen(request):
      File "/usr/lib/pymodules/python2.7/scrapy/dupefilter.py", line 46, in request_seen
        fp = self.request_fingerprint(request)
      File "/usr/local/lib/python2.7/dist-packages/scrapyjs/dupefilter.py", line 30, in request_fingerprint
        return splash_request_fingerprint(request)
      File "/usr/local/lib/python2.7/dist-packages/scrapyjs/dupefilter.py", line 20, in splash_request_fingerprint
        return dict_hash(request.meta['splash'], fp)
      File "/usr/local/lib/python2.7/dist-packages/scrapyjs/utils.py", line 14, in dict_hash
        h.update(dict_hash(value))
      File "/usr/local/lib/python2.7/dist-packages/scrapyjs/utils.py", line 18, in dict_hash
        h.update(unicode_to_str(value, 'utf8'))
      File "/usr/lib/pymodules/python2.7/scrapy/utils/python.py", line 97, in unicode_to_str
        raise TypeError('unicode_to_str must receive a unicode or str object, got %s' % type(text).__name__)
    exceptions.TypeError: unicode_to_str must receive a unicode or str object, got float

**Comment by kmike** [comment]
Thanks @gabll and @amirhadad! It should be fixed in scrapyjs==0.1.1 (i.e. float values should work as documented in 0.1.1).

**Comment by gabll** [comment]
It works correctly. Thank you!
