### ISSUE TITLE
OffsiteMiddleware TypeError: expected string or buffer

### ISSUE THREAD

**Issue by aidiss** [scrapy-plugins/scrapy-splash#153]
after I modified settings.py according to scrapy_splash documentation.
```
DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
DOWNLOADER_MIDDLEWARES = {
    'scrapy_crawlera.CrawleraMiddleware': 610,
    'scrapy_splash.SplashCookiesMiddleware': 723,
    'scrapy_splash.SplashMiddleware': 725,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
}
SPIDER_MIDDLEWARES = {
    'scrapy_splash.SplashDeduplicateArgsMiddleware': 100,
}
```

This error started to appear
```
2018-01-08 18:15:13 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ?.spider_opened of <scrapy.spidermiddlewares.offsite.OffsiteMiddleware object at 0x7f475a7630d0>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 65, in spider_opened
    self.host_regex = self.get_host_regex(spider)
  File "/usr/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 58, in get_host_regex
    if url_pattern.match(domain):
TypeError: expected string or buffer
```

**Comment by Gallaecio** [comment]
@aidiss Does it still happen? Could you share an URL affected by this issue?
