### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by zbury** [scrapy-plugins/scrapy-splash#165]
Using the command `docker run -p 8050:8050 scrapinghub/splash` results in the following error for me:

    Traceback (most recent call last):
      File "/app/bin/splash", line 3, in <module>
        from splash.server import main
      File "/app/splash/server.py", line 11, in <module>
        from splash.qtutils import init_qt_app
      File "/app/splash/qtutils.py", line 15, in <module>
        from PyQt5.QtWebKit import QWebSettings
    ImportError: /opt/qt59/5.9.1/gcc_64/lib/libQt5Quick.so.5: invalid ELF header

The first time I tried the command I didn't encounter this error..but subsequent attempts all result in that error.

**Comment by zbury** [comment]
Docker reset fixed it for me..
