### ISSUE TITLE
GET never used

### ISSUE THREAD

**Issue by dfishburn** [scrapy-plugins/scrapy-splash#74]
I was looking through middleware.py and see this:

```
    def process_request(self, request, spider):
        if 'splash' not in request.meta:
            return

        if request.method not in {'GET', 'POST'}:
            logger.warn(
                "Currently only GET and POST requests are supported by "
                "SplashMiddleware; %(request)s will be handled without Splash",
                {'request': request},
                extra={'spider': spider}
            )
            return request
        ....
        new_request = request.replace(
            url=splash_url,
            method='POST',
            body=body,
            headers=headers,
            priority=request.priority + self.rescheduling_priority_adjust
        )    
        self.crawler.stats.inc_value('splash/%s/request_count' % endpoint)
        return new_request
```

This means any requests sent from scrapy to splash will be POST requests.  This is confimed in the splash logs.

Problem I have is when CURL sends something to Splash, it uses a GET and the JavaScript is executed and the page is returned correctly.

If I issue the same CURL command with -X POST, the JavaScript is not executed (or takes too long) and I only get back HTML.

If there a reason this is not:

```
        new_request = request.replace(
            url=splash_url,
            method=request.method ,
            body=body,
            headers=headers,
            priority=request.priority + self.rescheduling_priority_adjust
        )    
```

If someone can offer me a workaround I would be forever grateful.

Here is the CURL request with GET (which works as expected):

```
sudo docker run -p 5023:5023 -p 8050:8050 -p :8051 scrapinghub/splash -v 3

curl -X GET 'http://localhost:8050/render.html?url=https://sapui5.hana.ondemand.com/sdk/docs/api/symbols/sap.html&iframe=1&html=1&png=1&width=1024&height=768&script=1&console=1&timeout=10&wait=0.5'

```

Last part of output from CURL:
`/b><span class="description"></span></div><div class="sectionItem itemName namespace static"><b class="icon" title="SAP UxAP"><a href="sap.uxap.html">uxap</a></b><span class="description">SAP UxAP</span></div><div class="sectionItem itemName namespace static"><b class="icon" title="Chart controls based on the SAP BI CVOM charting library"><a href="sap.viz.html">viz</a></b><span class="description">Chart controls based on the SAP BI CVOM charting library</span></div></div></div></div></div></body></html>
`
Splash Log

```
2016-06-04 16:55:17.101804 [network-manager] Headers received for https://sapui5.hana.ondemand.com/sdk/docs/api/images/namespace_obj.png
2016-06-04 16:55:17.109265 [network-manager] Finished downloading https://sapui5.hana.ondemand.com/sdk/docs/api/images/namespace_obj.png
2016-06-04 16:55:17.109562 [render] [140142934044512] mainFrame().initialLayoutCompleted
2016-06-04 16:55:17.124551 [render] [140142934044512] loadFinished: ok
2016-06-04 16:55:17.124953 [render] [140142934044512] loadFinished: disconnecting callback 0
2016-06-04 16:55:17.125597 [render] [140142934044512] loadFinished; waiting 500ms
2016-06-04 16:55:17.125880 [render] [140142934044512] waiting 500ms; timer 140142934153688
2016-06-04 16:55:17.642614 [render] [140142934044512] wait timeout for 140142934153688
2016-06-04 16:55:17.642988 [render] [140142934044512] _loadFinishedOK
2016-06-04 16:55:17.643053 [render] [140142934044512] stop_loading
2016-06-04 16:55:17.643170 [render] [140142934044512] HAR event: _onPrepareStart
2016-06-04 16:55:17.643264 [render] [140142934044512] getting HTML
2016-06-04 16:55:17.643447 [render] [140142934044512] HAR event: _onHtmlRendered
2016-06-04 16:55:17.643556 [pool] [140142934044512] SLOT 0 is closing <splash.qtrender.HtmlRender object at 0x7f7591ce2cc0>
2016-06-04 16:55:17.643620 [render] [140142934044512] close is requested by a script
2016-06-04 16:55:17.646391 [render] [140142934044512] cancelling 0 remaining timers
2016-06-04 16:55:17.646845 [pool] [140142934044512] SLOT 0 done with <splash.qtrender.HtmlRender object at 0x7f7591ce2cc0>
2016-06-04 16:55:17.650720 [events] {"client_ip": "172.17.0.1", "rendertime": 1.519012451171875, "fds": 22, "user-agent": "curl/7.47.0", "load": [0.28, 0.15, 0.14], "status_code": 200, "_id": 140142934044512, "args": {"height": "768", "script": "1", "console": "1", "url": "https://sapui5.hana.ondemand.com/sdk/docs/api/symbols/sap.html", "timeout": "10", "uid": 140142934044512, "wait": "0.5", "png": "1", "html": "1", "iframe": "1", "width": "1024"}, "method": "GET", "qsize": 0, "timestamp": 1465059317, "path": "/render.html", "maxrss": 74432, "active": 0}
2016-06-04 16:55:17.651474 [-] "172.17.0.1" - - [04/Jun/2016:16:55:17 +0000] "GET /render.html?url=https://sapui5.hana.ondemand.com/sdk/docs/api/symbols/sap.html&iframe=1&html=1&png=1&width=1024&height=768&script=1&console=1&timeout=10&wait=0.5 HTTP/1.1" 200 5562 "-" "curl/7.47.0"
2016-06-04 16:55:17.651792 [pool] SLOT 0 is available

```

Here is the CURL request using POST which does not render the JavaScript:

`curl -X POST 'http://localhost:8050/render.html?url=https://sapui5.hana.ondemand.com/sdk/docs/api/symbols/sap.html&iframe=1&html=1&png=1&width=1024&height=768&script=1&console=1&timeout=10&wait=0.5'
`

Last part of the CURL request, quite different from the GET request:

```
        </div><div class="snippetHighlightLine">
          <span class="lineno">136</span>
          <code class="code"> &#160; &#160; &#160; &#160;request_content_type = request.getHeader(b'content-type').decode('latin1')</code>
        </div><div class="snippetLine">
          <span class="lineno">137</span>
          <code class="code"> &#160; &#160; &#160; &#160;supported_types = ['application/javascript', 'application/json']</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>builtins.AttributeError</span>: <span>'NoneType' object has no attribute 'decode'</span>
  </div>
</div>

</body></html>
```

And the Splash log for this POST request:

```
2016-06-04 16:57:56.910757 [_GenericHTTPChannelProtocol,1,172.17.0.1] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
        why = self.lineReceived(line)
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 1688, in lineReceived
        self.allContentReceived()
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 1767, in allContentReceived
        req.requestReceived(command, path, version)
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 768, in requestReceived
        self.process()
    --- <exception caught here> ---
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 183, in process
        self.render(resrc)
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 234, in render
        body = resrc.render(self)
      File "/app/splash/resources.py", line 50, in render
        return Resource.render(self, request)
      File "/usr/local/lib/python3.4/dist-packages/twisted/web/resource.py", line 250, in render
        return m(request)
      File "/app/splash/resources.py", line 136, in render_POST
        request_content_type = request.getHeader(b'content-type').decode('latin1')
    builtins.AttributeError: 'NoneType' object has no attribute 'decode'

2016-06-04 16:57:56.930981 [-] "172.17.0.1" - - [04/Jun/2016:16:57:56 +0000] "POST /render.html?url=https://sapui5.hana.ondemand.com/sdk/docs/api/symbols/sap.html&iframe=1&html=1&png=1&width=1024&height=768&script=1&console=1&timeout=10&wait=0.5 HTTP/1.1" 500 5344 "-" "curl/7.47.0
```

Thanks for any input.

David

**Comment by kmike** [comment]
Hey @dfishburn,

> Problem I have is when CURL sends something to Splash, it uses a GET and the JavaScript is executed and the page is returned correctly. If I issue the same CURL command with -X POST, the JavaScript is not executed (or takes too long) and I only get back HTML.

Scrapy-splash uses [Splash HTTP API](http://splash.readthedocs.io/en/stable/api.html); POST requests has different format - they must use `application/json` content type and pass arguments in json-encoded body. In Splash they are strictly more powerful than GET because they allow to encode data to arrays/objects, and because there is no a limit on arguments length. Some Splash features are not available when using GET requests.

Note that these POST/GET we're talkling about are HTTP methods used to connect to Splash, not HTTP methods used to send requests to remote websites; the latter is controlled by [http_method](http://splash.readthedocs.io/en/stable/api.html#arg-http-method) argument or by parameters of [splash:go](http://splash.readthedocs.io/en/stable/scripting-ref.html?#splash-go) and alike functions. 

I think GET requests are more suited for quick testing or for embedding Splash results (e.g. screenshots) directly to webpages; to use all features clients should always prefer `application/json` POST requests.

> `builtins.AttributeError: 'NoneType' object has no attribute 'decode'`

This looks like a Splash bug, Splash should have returned error earlier.

**Comment by dfishburn** [comment]
Is this enough to report the problem, or do I need to do something else?

Thank you.

**Comment by kmike** [comment]
Hey @dfishburn, sorry for a long delay. I'm closing this issue in favor of https://github.com/scrapinghub/splash/issues/530 because the bug is in Splash, not in scrapy-splash.
