### ISSUE TITLE
Missing scheme in request url: render.html

### ISSUE THREAD

**Issue by ggoncalves** [scrapy-plugins/scrapy-splash#95]
Hi, already running docker. Trying to do a simple test, as described in the tutorial:

```py
import scrapy
from scrapy_splash import SplashRequest

class QuotesSpider(scrapy.Spider):
    name = "quotes"

    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com:80/page/1/',
            'http://quotes.toscrape.com:80/page/2/',
        ]
        for url in urls:
            yield SplashRequest(url, self.parse, args={'wait': 0.5})
            #yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page
        with open(filename, 'wb') as f:
            f.write(response.body)
        self.log('Saved file %s' % filename)
```

Any other test using SplashRequest generates the same error below:

(python-scrappy) Crosby:tutorial ggoncalves$
(python-scrappy) Crosby:tutorial ggoncalves$ scrapy crawl quotes
2016-12-14 00:14:55 [scrapy] INFO: Scrapy 1.2.2 started (bot: tutorial)
2016-12-14 00:14:55 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'tutorial.spiders', 'SPIDER_MODULES': ['tutorial.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'tutorial'}
2016-12-14 00:14:55 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-12-14 00:14:55 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy_splash.SplashCookiesMiddleware',
 'scrapy_splash.SplashMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-12-14 00:14:55 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy_splash.SplashDeduplicateArgsMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-12-14 00:14:55 [scrapy] INFO: Enabled item pipelines:
[]
2016-12-14 00:14:55 [scrapy] INFO: Spider opened
2016-12-14 00:14:55 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-12-14 00:14:55 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-12-14 00:14:56 [scrapy] DEBUG: Crawled (404) <GET http://quotes.toscrape.com:80/robots.txt> (referer: None)
2016-12-14 00:14:56 [scrapy] ERROR: Error downloading <GET http://quotes.toscrape.com:80/page/1/ via http://quotes.toscrape.com:80/page/1/>
Traceback (most recent call last):
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 358, in process_request
    priority=request.priority + self.rescheduling_priority_adjust
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 93, in replace
    return cls(*args, **kwargs)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy_splash/request.py", line 76, in __init__
    **kwargs)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 57, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: render.html
2016-12-14 00:14:56 [scrapy] ERROR: Error downloading <GET http://quotes.toscrape.com:80/page/2/ via http://quotes.toscrape.com:80/page/2/>
Traceback (most recent call last):
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy_splash/middleware.py", line 358, in process_request
    priority=request.priority + self.rescheduling_priority_adjust
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 93, in replace
    return cls(*args, **kwargs)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy_splash/request.py", line 76, in __init__
    **kwargs)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/Users/ggoncalves/dev/python-crawler/python-scrappy/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 57, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: render.html
2016-12-14 00:14:56 [scrapy] INFO: Closing spider (finished)
2016-12-14 00:14:56 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 2,
 'downloader/exception_type_count/exceptions.ValueError': 2,
 'downloader/request_bytes': 227,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 368,
 'downloader/response_count': 1,
 'downloader/response_status_count/404': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 12, 14, 3, 14, 56, 729779),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 2,
 'log_count/INFO': 7,
 'response_received_count': 1,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'start_time': datetime.datetime(2016, 12, 14, 3, 14, 55, 259052)}
2016-12-14 00:14:56 [scrapy] INFO: Spider closed (finished)

Where should I start?

**Comment by kmike** [comment]
Hey, are you sure all scrapy-splash configuration options are set correctly? What is e.g. in SPLASH_URL?

**Comment by ggoncalves** [comment]
Hello Mike, I'm sorry. It was a problem in the docker-machine. The SPLASH_URL was set, but pointing to a Splash instance running on the local machine instead of the docker machine.

Once I solve the docker-machine running issue, I was able to run the scrapy-splash properly.

Thank you!
